// <auto-generated />
namespace CondominioEstribo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class terceira1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(terceira1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707061722026_terceira1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
